export const enum AppAction {
    INIT = '@@redux/INIT',
    LOAD_DATA_TYPE_1 = 'LOAD_DATA_TYPE_1',
    LOAD_DATA_TYPE_1_SUCCESS = 'LOAD_DATA_TYPE_1_SUCCESS',
    LOAD_DATE_TYPE_1_ERROR = 'LOAD_DATA_TYPE_1_ERROR',
    LOAD_DATA_TYPE_2 = 'LOAD_DATA_TYPE_2',
    LOAD_DATA_TYPE_2_SUCCESS = 'LOAD_DATA_TYPE_2_SUCCESS',
    LOAD_DATE_TYPE_2_ERROR = 'LOAD_DATA_TYPE_2_ERROR',
    LOAD_DATA_TYPE_3 = 'LOAD_DATA_TYPE_3',
    LOAD_DATA_TYPE_3_SUCCESS = 'LOAD_DATA_TYPE_3_SUCCESS',
    LOAD_DATE_TYPE_3_ERROR = 'LOAD_DATA_TYPE_3_ERROR'
}
